app:
  resource: "@AppBundle/Controller/"
  type:     annotation

home:
  path: /
  defaults: { _controller: AppBundle:Default:index }

users:
  path: /users/
  defaults: { _controller: AppBundle:User:list }
user_profile:
  path: /user/profile/{userId}
  defaults: { _controller: AppBundle:User:profile }
user_edit:
  path: /user/edit/{userId}
  defaults: { _controller: AppBundle:User:edit }
user_add:
  path: /user/add
  defaults: { _controller: AppBundle:User:create }
user_create:
  path: /user/create
  defaults: { _controller: AppBundle:User:add }
