# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory: ~
#                users:
#                  sirfoomy:
#                      password: $2y$12$.5lX1He.68N7kQoK.RDVCOp.AZ5zMxIgK7aFTkQNDtZMj6SNSa.C2
#                      roles: 'ROLE_USER'
#                  admin:
#                      password: $2y$12$.5lX1He.68N7kQoK.RDVCOp.AZ5zMxIgK7aFTkQNDtZMj6SNSa.C2
#                      roles: 'ROLE_ADMIN'
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username

    encoders:
#        Symfony\Component\Security\Core\User\User:
#                algorithm: bcrypt
#                cost: 12
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html

            provider: our_db_provider

    access_control:
        - { path: ^/users/, roles: ROLE_ADMIN }
        - { path: ^/user/add/, roles: ROLE_ADMIN }
        - { path: ^/user/profile/^, roles: ROLE_USER }
        - { path: ^/user/edit/^, roles: ROLE_USER }
        - { path: ^/user/logout/, roles: ROLE_USER }
